name = "Select spawn locations"
uid = "ssl-v01"
version = 1
copyright = ""
description = "choose your position before spawn"
author = "4z0t"
icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
